POST http://localhost:10000/fepi/cursos/create HTTP/1.1
Content-Type: application/json

{
    "name": "Nivel basico de uñas acrilicas",
    "description": "Se realizan procesos basicos de acrilicas",
    "time": 28,
    "state": "No disponible"
}


###
//Mostrar un curso por su ID
GET http://localhost:10000/fepi/cursos/ HTTP/1.1
Content-Type: application/json


###
//Mostrar todos los datos
GET http://localhost:10000/fepi/cursos/665d388d9506d0faf32ba0e1 HTTP/1.1
Content-Type: application/json


###
PUT http://localhost:10000/fepi/cursos/6673817193019c57295ceeef HTTP/1.1
Content-Type: application/json

{
   "name": "Nivel basico de uñas acrilicas",
    "description": "Se realizan procesos basicos de acrilicas",
    "time": 28,
    "state": "No disponible",
    "assigned": false
}


//Mostrar un curso por su ID


###
//Eliminar un curso por su ID
DELETE http://localhost:10000/fepi/cursos/665fb33f4808fec86e68ad1a HTTP/1.1
